### ISSUE TITLE
OSDK does not support flavors of 3.2 firmware

### ISSUE THREAD

**Issue by taurean1192** [dji-sdk/Onboard-SDK#88]
In continuation of similar issues I have faced previously, the SDK's sample has failed to obtain control of my DJI A3 FC. It flashes the same error - RC not in P mode, while my RC is in single flight mode - P.

The compilation raises no error. I am running the A3 FW 1.7. The system is a Raspberry Pi 3 (ARM 64bit) running Ubuntu 16.04.
![sdk_err2](https://cloud.githubusercontent.com/assets/24839780/22248572/2ff877d0-e265-11e6-85e5-a87bc43c1470.jpg)

**Comment by rohitsantdji** [comment]
For non-x86 systems, a bug in osdk-wrapper incorrectly shows successful activation while the system may not actually be activated; the sample might have failed at any point before attempting to obtaining control. This bug will be fixed in an upcoming release, but till then you cannot rule out the possibility that the connections are incorrect, the baud rate does not match, the buffering on your USB-serial adapter is not correctly configured or activation has not gone through. 

To help debug - could you try the same sample on an x86 system with the same connections, and post your findings here?

**Comment by taurean1192** [comment]
Hey @rohitsantdji I had thought of the other possible errors as well hence I checked all of that and ran the sample with different baud rates, loose connections, checking serial buffer and the others. All of them checked out. This shows the same thing on my x64 laptop. So two platforms won't show the same problems after so much verification.

Also this issue is persistent since v3.18 of the SDK, then I tried doing it on the x86 ARM, but the same issues prevailed. Now it is difficult to find the 16.04 OS distro for the x86 version of ARM, the existing one often faces bugs upon updating.

**Comment by rohitsantdji** [comment]
Okay. Output on a x64 laptop is also good enough for our debugging purposes.

**Comment by rohitsantdji** [comment]
A screenshot of DJI Assistant 2's SDK page and the default page will also be helpful.

**Comment by jvgomez** [comment]
For completeness, this issue seems to be a general problem. I am facing the same issue as well (I cannot make the demo code work in a x64 PC), but I have seen some other posts with the same/similar problems:

http://forum.dev.dji.com/thread-33009-1-1.html
http://forum.dji.com/thread-81078-1-1.html

**Comment by taurean1192** [comment]
@rohitsantdji please see below the output for the x86 ARM machine, running Ubuntu 16.04. It gives the same error. 
![x86_err](https://cloud.githubusercontent.com/assets/24839780/22290591/b2e7ecd0-e327-11e6-8373-4fbc97910222.jpg)

Also as you requested the SDK settings using the DJI Assistant 2 software
![a3_stats](https://cloud.githubusercontent.com/assets/24839780/22290598/c64aea02-e327-11e6-8462-7097b89dad98.png)

**Comment by rohitsantdji** [comment]
@jvgomez Thanks for the additional links.

@taurean1192 it seems from your screenshot that this is still an ARM computer. (by [x86 ARM](http://stackoverflow.com/questions/14794460/how-does-the-arm-architecture-differ-from-x86) maybe you meant 32-bit ARM?). If you get a chance, please try it on Ubuntu 16.04 on an Intel/AMD x86_64 computer and let us know if you are getting a "Your SDK Version in User_config.h does not match the one reported by the drone." error.

To give everyone an update on this: FW 1.7.0.0 introduces new version strings for N3 and for A3, and the SDK currently does not have support for this. This causes activation itself to fail, and a good way to check this is to run the sample on an x86 machine where the serial driver can implement various levels of checks. Expect a hotfix soon.

**Comment by jvgomez** [comment]
@rohitsantdji is there any expected date for the hotfix? This is blocking some other things in my case. Thank you.

**Comment by FLDataTeK** [comment]
Agreed we need to know when to expect the hot fix. This issue has halted our development and we need to get things moving.  We are going to load up a x86 board this morning so we can make some progress but we need a solution to this issue ASAP so we can continue down the proper path as we have already wasted to much time on this.

**Comment by rohitsantdji** [comment]
Hotfix is in testing and will be released by tomorrow (02/02). Apologize for the delay, guys - our tests discovered some latent issues when run on Ubuntu 14.04 so we're fixing those.

**Comment by FLDataTeK** [comment]
We tried this on a x86 (Intel Atom) based machine and seem to be getting further along, but we are unable to activate the SDK. 

x86 Intel Atom
Ubuntu 14.04
USB to Serial cable going to the API port on the A3
The PC has internet connectivity
Using the current versionA3_32 = (MAKE_VERSION(3, 2, 15, 37)); in DJI_Version.h  as provided by DJI dev support

FrSky Taranis Plus with SBUS receiver connected and turned on and showing in P mode in Assistant 2

It does look like it is talking to the FC now, but we are unable to activate. We have ran a make & make clean 

![img_0300](https://cloud.githubusercontent.com/assets/13739771/22516817/0a2b1c0e-e875-11e6-8224-c54aa9709199.JPG)

**Comment by rohitsantdji** [comment]
@FLDataTeK you'll need a LightBridge2 RC with DJI GO connected to the internet to activate the device.

**Comment by FLDataTeK** [comment]
We were  told the last SDK and Assistant 2 update removed this requirement for LB2.

**Comment by rohitsantdji** [comment]
If anyone (@taurean1192 @jvgomez ) is blocked by this, please follow the support suggestion to @FLDataTeK   (set versionA3_32 = (MAKE_VERSION(3, 2, 15, 37)); in DJI_Version.h); the fix implements a new automated versioning system that won't require you to find our what version your flight controller is running.

**Comment by rohitsantdji** [comment]
@FLDataTeK does the program return the same error when run multiple times? And are you running Assistant 2 v1.0.9-2?

**Comment by FLDataTeK** [comment]
@rohitsantdji 

Yes we have ran multiple times and are running the latest firmware rev and Assistant v1.0.9-2

**Comment by rohitsantdji** [comment]
@FLDataTeK The current implementation of the non-LB2 activation can activate without an LB2 RC, but still requires an LB2 air system connected to the A3. This requirement will be removed in the next version.

**Comment by jvgomez** [comment]
@rohitsantdji thanks for the update!

**Comment by natelannan-osu** [comment]
I still got a mismatch error using versionA3_32 = (MAKE_VERSION(3, 2, 15, 37));
I'm running ubuntu 14.04 on an ARM BeagleBone Black

just fyi for others running similar HW

**Comment by rohitsantdji** [comment]
Please try the 3.2.1 release and report any issues. Thanks!

**Comment by natelannan-osu** [comment]
@rohitsantdji 
I don't think parseDroneVersionInfo() is working correctly for me.  I am getting null characters in buf after memcpy(buf, ackPtrIncoming, 64);.  Wondering if something is going screwy with ptemp in getDroneVersion().  going to look into it further, but if you have suggestions that would be grand.

HW: M600
FW: V1.0.0.80
Assistant: V1.0.9-2
SDK: 3.2.1
Onboard device:  ARM BeagleBone Black running Ubuntu 14.04

output (I added some debug statements):
root@arm:~/newSDK/Onboard-SDK/build/bin# ./djiosdk-linux-sample -interactive
User Configuration read successfully.

These are your User_Config settings.
Serial port = /dev/ttyO4
Baudrate = 230400
App ID: *****************************
App Key: ***************************

Does everything look correct? If not, navigate to Linux/UserConfig.txt and make changes.

STATUS init,line 51: Attempting to open device /dev/ttyO4 with baudrate 230400...
STATUS init,line 60: ...Serial started successfully.
before getDroneVersion(1)
parseDroneVersionInfo:
buf[0]: 0x00
ackPtrIncoming + 0: 0x00
buf[1]: 0x00
ackPtrIncoming + 1: 0x00
buf[2]: 0x00
ackPtrIncoming + 2: 0x00
buf[3]: 0x00
ackPtrIncoming + 3: 0x00
buf[4]: 0x00
ackPtrIncoming + 4: 0x00
buf[5]: 0x00
ackPtrIncoming + 5: 0x00
buf[6]: 0x00
ackPtrIncoming + 6: 0x00
buf[7]: 0x00
ackPtrIncoming + 7: 0x00
buf[8]: 0x00
ackPtrIncoming + 8: 0x00
buf[9]: 0x00
ackPtrIncoming + 9: 0x00
buf[10]: 0x00
ackPtrIncoming + 10: 0x00
buf[11]: 0x00
ackPtrIncoming + 11: 0x00
buf[12]: 0x00
ackPtrIncoming + 12: 0x00
buf[13]: 0x00
ackPtrIncoming + 13: 0x00
buf[14]: 0x00
ackPtrIncoming + 14: 0x00
buf[15]: 0x00
ackPtrIncoming + 15: 0x00
buf[16]: 0x00

In the previous SDK this info was coming down in getDroneVersion():
my debug from 3.2.0:
version_name:  v1.0 BETA PM820V3-03.02.10.00
version_ack:  65281
version_crc:  808924720
version_ID:  -1094574206
version:  50462720

thanks for your time

**Comment by rohitsantdji** [comment]
Could you uncomment the print block at the end of parseDroneVersionInfo() and report the output?

**Comment by natelannan-osu** [comment]
It never makes it that far.  it jumps out while parsing the name:

  while (*ackPtr != ' ') {
    ackPtr++;
    if (ackPtr - startPtr > 64) {
      API_LOG(serialDevice, ERROR_LOG, "Drone version was not obtained. Please restart the program or call getDroneVersion\n");
      return false;
    }
} //! Found first space ("SDK-v1.x")

I can take out those returns and see what we get if you want

**Comment by rohitsantdji** [comment]
At first glance this looks like a partly unrelated serial driver issue - we do not test on BeagleBone, so it is difficult to debug this offline. On ARM devices the serial driver does not validate the serial connection, so zeros on the line could be caused by any layer of the serial stack. Results of a test from an x86 computer or a Manifold would be helpful.

Is OSDK 3.2.0 returning useful information with this setup as it is right now?

**Comment by natelannan-osu** [comment]
It was yielding useful data yesterday.  The only thing I did today was clone 3.2.1, add my user_config.h and build.  Drone stayed unchanged.  I am away from my work station right now so I will have to revert to 3.2.0 when u get back

**Comment by rohitsantdji** [comment]
A small fix has been issued to address a bug in M600 and M600 Pro aircraft running FW 1.0.0.80, please try that if you own one of these aircraft.

**Comment by rohitsantdji** [comment]
Fixed in OSDK 3.2.1. Please re-open if this is not the case for you.

**Comment by MonkaSebastian** [comment]
Hey,
last week there wasn't any problem with the onboard sdk but now there is.
The last time when it worked I used the OSDK 3.2 but suddenly it failed to obtain control.
(Do I need to activate through the internet again, when I change and compile my program again?)

I tried so.
I changed my SDK to 3.2.2 deleted my version: versionM100_31.
But now I get this error with the native program.



root@EMC2_LVTTL:/mnt# ./EMC2_Matrice4.elf -interactive
User Configuration read successfully. 

These are your User_Config settings.
Serial port = /dev/ttyUL1
Baudrate = 230400
App ID: ......
App Key: .....

Does everything look correct? If not, navigate to Linux/UserConfig.txt and make changes.

STATUS init,line 51: Attempting to open device /dev/ttyUL1 with baudrate 230400...
STATUS init,line 60: ...Serial started successfully.
ERROR parseDroneVersionInfo,line 246: Drone version was not obtained. Please restart the program or call getDroneVersion

Attempting activation..
ERROR parseDroneVersionInfo,line 246: Drone version was not obtained. Please restart the program or call getDroneVersion
Automatic activation successful.
Failed to obtain control.
Your RC mode switch is not in mode F. (Is the RC connected and paired?)
This program will exit now.

**Comment by taurean1192** [comment]
I tried with SDK v3.2.1 today, it still isn't working properly on mine. I am using ARM 32 bit, Ubuntu 16.04.
The output is as follows - 

pi@pi-desktop:~sudo ./djiosdk-linux-sample -interactive
User Configuration read successfully.

These are your User_Config settings.
Serial port = /dev/ttyUSB0
Baudrate = 115200
App ID: ......
App Key: .....

Does everything look correct? If not, navigate to Linux/UserConfig.txt and make changes.

STATUS init,line 51: Attempting to open device /dev/ttyUSB0 with baudrate 115200...
STATUS init,line 60: ...Serial started successfully.
ERROR parseDroneVersionInfo,line 246: Drone version was not obtained. Please restart the program or call getDroneVersion

Attempting activation..
ERROR parseDroneVersionInfo,line 246: Drone version was not obtained. Please restart the program or call getDroneVersion
Automatic activation successful.
Failed to obtain control.
Your RC mode switch is not in mode F. (Is the RC connected and paired?)
This program will exit now.


What to do? 3 months since purchasing but still stuck at the same point

**Comment by rohitsantdji** [comment]
@taurean1192 based on the response of other users and community members it appears that the issue has in general been resolved. It sounds like the issue you are seeing has something to do with the particular setup that you have. Raspberry Pi platform support is still experimental - we can help you debug this. Are you using a Pi 2?

**Comment by taurean1192** [comment]
@rohitsantdji yes I am using Pi 2, I also have Pi 3 with me.

On 13-Feb-2017 23:02, "Rohit Sant" <notifications@github.com> wrote:

@taurean1192 <https://github.com/taurean1192> based on the response of
other users and community members it appears that the issue has in general
been resolved. It sounds like the issue you are seeing has something to do
with the particular setup that you have. Raspberry Pi platform support is
still experimental - we can help you debug this. Are you using a Pi 2?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dji-sdk/Onboard-SDK/issues/88#issuecomment-279461868>,
or mute the thread

**Comment by taurean1192** [comment]
@rohitsantdji I tried testing the Raspberry-support version of the SDK on Pi2, it gave the following error.

![pi2_err](https://cloud.githubusercontent.com/assets/24839780/23056005/1fdaec7c-f50f-11e6-9840-3cd71836c991.png)


Please advise the way forward

**Comment by taurean1192** [comment]
@MonkaSebastian  what is your OES?

**Comment by MonkaSebastian** [comment]
Hey I use "Petalinux", it is a Yocto based linux for Xilinx FPGAs.
The cpu is also arm 32.
Its a really random error. Proof your UART connection and your connection between FC, controller and internet.
Good luck!

**Comment by taurean1192** [comment]
@MonkaSebastian thanks. I am looking for a SoC to run this setup of A3 on. Spent months trying on RPi. Any SoC you can suggest? @rohitsantdji  can you suggest any SoC running Linux?

**Comment by FLDataTeK** [comment]
@taurean1192 We have started using Intel Atom based Minnowboard with success. We have successfully test flown using the SDK demos and now are working on getting our software moved over to it and flight tested.

**Comment by taurean1192** [comment]
@FLDataTeK any particular version of the MinnowBoard and the OS you are using that you can tell me?

**Comment by adamwathieu** [comment]
Hey,
Did anybody figure out how to fix this issue. I have some deadlines, and I need to get this fixed so I can move on to the real stuff:
https://github.com/dji-sdk/Onboard-SDK/issues/143
Thanks.
